# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: polkit.spec

# add or remove files that should be synced
files_to_sync:
    - polkit.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: polkit
# downstream (Fedora) RPM package name
downstream_package_name: polkit

actions:
  post-upstream-clone:
    - "wget https://src.fedoraproject.org/rpms/polkit/raw/rawhide/f/polkit.spec -O polkit.spec"
    - "sed -ri '/^Patch[0-9]+/d' polkit.spec"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
